solita/ara-etp

- etp-core/etp-backend/src/main/clj/solita/etp/service/aineisto.clj
- etp-core/etp-backend/src/test/clj/solita/etp/service/aineisto_test.clj
An alternative to this would be to create a CloudFront function to remove the /api/signed part but it seems that it would introduce unnecessary complexities
> AE-2038: Set the keys for aineistot to correspond to the API paths

- etp-core/etp-backend/src/test/clj/solita/etp/service/valvonta_kaytto_test.clj
- etp-core/etp-db/src/main/sql/migration/repeatable/vk_template/r-0-vk-toimenpidetype.sql
- etp-front/src/pages/valvonta-kaytto/new-toimenpide-dialog.svelte
AE-1923: 
Mark older käytönvalvonta toimenpidetypes that should have comments as allowing comments in db
- Previously there has been a logic in frontend to allow comments when there are no document templates attached to the toimenpidetype
- Now we change the the older toimenpidetypes to use the flag allow_comments that is saved to database
- Toimenpidetypes changed now are "Valvonnan aloitus", "Käskypäätös" and "Valvonnan lopetus"
Remove condition in käytönvalvonta new-toimenpide-dialog to show commenting when there are no document template
- Commenting is now only allowed for toimenpidetypes that have it configured to be allowed in vk_toimenpidetype db table
> AE-1923: Mark older käytönvalvonta toimenpidetypes that should have comments as allowing comments in db

- etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_kaytto.clj
Generating the valvonta.csv used inner join instead of left join and thus dropped some lines, which after discussion with the customer were added to the csv. No lines missing because of recent changes were found.
> AE-1968: Add missing valvonta lines to exported CSV

- etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_kaytto.clj
- Field is not saved to database so it's not present in the saved toimenpide, only in the toimenpide-add request body
> AE-2098: Read bypass-asha parameter from request body instead of saved toimenpide

- etp-core/etp-backend/src/main/clj/solita/etp/service/asha.clj
- etp-core/etp-backend/src/test/clj/solita/etp/service/asha_test.clj
AE-2014: Check if Käsittely toimenpide is already ready to determine if uudelleenkäsittele asia transition needs to be used in käytönvalvonta
- Previously it was checked that we were moving from an unfinished tiedoksianto ja toimeenpano toimenpide but this wasn't right as the state of that toimenpide is not necessarily unfinished
> AE-2014: Check if Käsittely toimenpide is already ready to determine if uudelleenkäsittele asia transition needs to be used in käytönvalvonta

- etp-core/etp-backend/src/main/sql/solita/etp/db/valvonta-kaytto.sql
- etp-core/etp-backend/src/test/clj/solita/etp/service/valvonta_kaytto_test.clj
AE-1969: Allow using both only-uhkasakkoprosessi and include-closed query options as true when searching for käytönvalvonnat
> AE-1969: Allow using both only-uhkasakkoprosessi and include-closed query options as true when searching for käytönvalvonnat

- etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_kaytto.clj
- etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_kaytto/toimenpide.clj
AE-2105: Use all osapuolet in käytönvalvonta for kehotus toimenpide, others use only owners
- Fixes kiinteistönvälittäjät appearing in asha in toimenpidetypes where they are not needed
> AE-2105: Use all osapuolet in käytönvalvonta for kehotus toimenpide, others use only owners

- etp-core/etp-backend/Dockerfile
- etp-core/etp-db/Dockerfile
- Ensures exact image is used every time
- Ensures that Renovate will find updates for these images, previously it couldn't understand the funky versioning in the tag
> Update Clojure build image and pin docker image version with digest

- etp-core/etp-backend/deps.edn
com.cognitect.aws/api is using the fixed jetty version. No need to override anymore.
> Remove jetty replacement

- e2e-tests/cypress/docker-compose.yml
- e2e-tests/cypress/start-e2e-env.sh
- etp-core/docker/docker-compose.yml
Docker compose does not care about exit codes of jobs. Migration runner failed sometimes, perhaps because DB was not ready.
Added a check for migration-runner exit code in e2e start script.
Added a healthcheck for db in compose, and require it to be healthy before migration runner is run.
> Fix flakyness in e2e test setup

- etp-front/src/pages/valvonta-kaytto/osapuolet.js
In Ramda update all toimitustapa detectors were changed to have the same id.
> Fix toimitustapa functions

- etp-public/package-lock.json
- etp-public/package.json
- etp-public/postcss.config.js
Autoprefixer is already included in postcss-preset-env. No need to bring it in separately.
> Remove autoprefixer

- etp-public/src/components/button.svelte
- etp-public/src/components/buttonlink.svelte
- etp-public/src/components/container.svelte
- etp-public/src/components/nav-button.svelte
Earlier some Tailwind class names were generated dynamically, which broke some styles when purge comments were removed.
Simplify code by removing dynamic name generation.
> Remove dynamic generation of Tailwind classes

- etp-front/src/pages/valvonta-kaytto/toimenpiteet.js
AE-2191: Use only templates marked as valid to determine the default template for käytönvalvonta toimenpide
- Previously there have been multiple templates in use for some toimenpidetypes. These have now been marked as no longer valid so they can't be selected, but they were still taken into account when determining the default template (the only one when there's no others)
> AE-2191: Use only templates marked as valid to determine the default template for käytönvalvonta toimenpide

- etp-public/src/components/input-search.svelte
Tailwind upgrade moved opacity to text-[color]/[opacity] format. As a consequence, placeholder text got default opacity of 100%, whereas before it was determined by browser defaults.
Fixed by setting a sensible looking opacity of 70% for placeholder text.
> Set explicit input placeholder opacity

- e2e-tests/cypress/.gitignore
- e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
- etp-core/etp-backend/src/main/clj/solita/etp/service/energiatodistus.clj
- etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_kaytto.clj
- etp-core/etp-backend/src/main/sql/solita/etp/db/energiatodistus.sql
- etp-core/etp-backend/src/test/clj/solita/etp/service/energiatodistus_history_test.clj
- etp-core/etp-backend/src/test/clj/solita/etp/service/energiatodistus_pdf_test.clj
- etp-core/etp-backend/src/test/clj/solita/etp/test_data/energiatodistus.clj
- etp-core/etp-backend/src/test/clj/solita/etp/test_data/generators.clj
- etp-core/etp-backend/src/test/clj/solita/etp/valvonta_kaytto/valvonta_csv_test.clj
Add to käytönvalvonta csv information during what toimenpide energiatodistus was acquired during the valvonta, if energiatodistus has been acquired for the building.
> AE-2063: Add energiatodistus hankittu column to käytönvalvonta csv

- etp-front/src/pages/header/language-select.svelte
Broken in Tailwind upgrade for unknown reason.
> Fix letter spacing on language select in etp-front

- etp-front/src/pages/viesti/viestiketju.svelte
It seems after Tailwind upgrade if both text-primary and text-error are set former wins instead of latter.
Fixed by setting only one of the classes.
> Fix unread symbol on messages

- etp-front/src/pages/energiatodistus/energiatodistus-haku/querybuilder/queryblock.svelte
After Webpack 5 upgrade something broke, update that queryblock sends causes it to trigger again.
Fixed by not sending the event input value is the same as before.
> Fix energiatodistushaku infinite loop

- etp-front/src/pages/valvonta-oikeellisuus/existing-toimenpide.svelte
Broken in the Webpack 5 upgrade commit. Perhaps load and save got called in different order earlier.
saveToimenpide calls load so there is no need for reactive load. Fixed by setting it to call only on page load.
> Fix valvontamuistio

- etp-core/etp-backend/src/main/clj/solita/etp/common/audit_log.clj
- etp-core/etp-backend/src/main/clj/solita/etp/core.clj
- etp-core/etp-backend/src/main/resources/logback.xml
- etp-core/etp-backend/src/test/resources/logback.xml
Logger in audit-log ns can be used to log with a known prefix. The logs are then redirected to a different place in AWS.
> Implement audit logging for signatures

- etp-core/etp-backend/src/main/sql/solita/etp/db/energiatodistus-destruction.sql
- etp-core/etp-backend/src/test/clj/solita/etp/service/energiatodistus_destruction_test.clj
voimassaolo_paattymisaika is timestamptz and now() returns a timestamptz so there is no need to convert the timezone.
> Consider the voimassaolo_paattymisaika as exact timestamp

- etp-core/etp-backend/src/main/clj/solita/etp/service/laskutus.clj
This reverts commit c010c1f996121be084563e8b9dfa0e8004e27104.
> Revert "AE-2301: Change 7010 -> 7000 in Kieku messages"

- etp-core/etp-backend/src/dev/clj/user.clj
- etp-core/etp-backend/src/main/clj/solita/etp/api/aineisto.clj
- etp-core/etp-backend/src/main/clj/solita/etp/api/public_csv.clj
- etp-core/etp-backend/src/main/clj/solita/etp/handler.clj
- etp-core/etp-backend/src/main/clj/solita/etp/service/aineisto.clj
- etp-core/etp-backend/src/main/clj/solita/etp/service/csv_to_s3.clj
- etp-core/etp-backend/src/test/clj/solita/etp/service/aineisto_test.clj
- etp-core/etp-backend/src/test/clj/solita/etp/service/csv_to_s3_test.clj
Aika pitkälti olemassaolevaa totetusta mukaillen toteutettu uusi sisäinen endpoint julkisen puolen CSV-tiedostojen lataamiselle S3:een.
Aineisto.clj -tiedostossa tulee nyt hieman duplikaatti koodia ja ajattelin yhtenäistää toteutusta kunhan saan palautetta että olenhan tajunnut toiminnallisuuden oikein.
Testasin MinIO Consolen kautta ja näytti tulevan oikean kansion alle CSV:t
> Add new internal endpoint for updating public csv data into S3

- etp-front/package.json
- etp-front/webpack.config.js
As an alternative for using a browser extension, this allows setting the target user's email address into the ETP_DEV_FRONT_USER env variable and having the devserver proxy set authentication headers to match, based on content in modheaders.json.
> AE-2134 Set headers in the devserver proxy

- etp-front/src/pages/tietosuojaseloste/energiatodistusrekisteri/fi.svelte
- etp-front/src/pages/tietosuojaseloste/energiatodistusrekisteri/sv.svelte
- etp-front/src/pages/tietosuojaseloste/laatijarekisteri/fi.svelte
- etp-front/src/pages/tietosuojaseloste/laatijarekisteri/sv.svelte
- etp-front/src/pages/tietosuojaseloste/valvontatietorekisteri/fi.svelte
- etp-front/src/pages/tietosuojaseloste/valvontatietorekisteri/sv.svelte
- etp-public/src/pages/energiatodistusrekisterin-aineistopalvelu-fi.svelte
- etp-public/src/pages/energiatodistusrekisterin-aineistopalvelu-sv.svelte
- etp-public/src/pages/energiatodistusrekisterin-rajapintapalvelu-fi.svelte
- etp-public/src/pages/energiatodistusrekisterin-rajapintapalvelu-sv.svelte
- etp-public/src/pages/tietojenluovutus-ja-rajapinnat-fi.svelte
- etp-public/src/pages/tietojenluovutus-ja-rajapinnat-sv.svelte
- etp-public/src/pages/tietosuojaseloste-aineistopalvelun-kayttajarekisteri-fi.svelte
- etp-public/src/pages/tietosuojaseloste-aineistopalvelun-kayttajarekisteri-sv.svelte
- etp-public/src/pages/tietosuojaseloste-energiatodistusrekisteri-fi.svelte
- etp-public/src/pages/tietosuojaseloste-energiatodistusrekisteri-sv.svelte
- etp-public/src/pages/tietosuojaseloste-laatijarekisteri-fi.svelte
- etp-public/src/pages/tietosuojaseloste-laatijarekisteri-sv.svelte
- etp-public/src/pages/tietosuojaseloste-valvontatietorekisteri-fi.svelte
- etp-public/src/pages/tietosuojaseloste-valvontatietorekisteri-sv.svelte
Muutettu julkisen ja priva puolen selosteiden tekstit Varke-muotoon. Lisäksi päivitetty sähköpostiosotteita sekä linkkejä. Saavutettavuusselostetta ei ole päivitetty sillä viestinnän yhteissähköpostia ei ole tiedossa.
> AE-2431: Varke -tekstimuutokset selosteet 

- etp-front/src/pages/valvonta-kaytto/valvonnat.svelte
The goal of the rearrangement is to have browser history work sensibly
when search parameters are changed, meaning that you can get
to your previous search by pressing the back button.
Oikeellisuuden valvonta already had this working correctly, so the setup in
this branch just ports that to käytönvalvonta.
> AE-1662 Redo query processing in käytönvalvonta

- etp-core/etp-backend/src/main/clj/solita/etp/config.clj
Set max-lifetime to 10 minutes by default in db config. Also introduce "DB_MAX_LIFETIME_MS" to be able to fine-tune it later.
> AE-1851: Set max-lifetime to 10 minutes by default in db config

- etp-core/etp-backend/src/test/clj/solita/etp/service/laatija_test.clj
- etp-core/etp-db/src/main/sql/migration/v5-release-1.1/v5.49-add-ppp-patevyystaso.sql
- etp-front/src/pages/laatija/laatijat.svelte
Migraatiolla lisätty kaksi uutta pätevyystasoa.
Nykyiset tasot ovat kovakoodattuna table-laatijahaku-filter.svelte -tiedostossa joten uudet pätevyystasot eivät vielä tule näkyviin.
Kirjautumispalvelun puolella laatijapätevyydet tulivat dynaamisesti näkyviin laatijahaun valikkoon, mutta ne on toistaiseksi suodatettu pois
> AE-2542: Tietomallin laajennus kattamaan PPP:n laatijapätevyys

- etp-front/src/App.svelte
- etp-front/src/pages/energiatodistus/energiatodistukset.svelte
- etp-front/src/pages/footer/Footer.svelte
- etp-front/src/pages/laatija/laatija-form.svelte
- etp-front/src/pages/laatija/laatijat.svelte
- etp-front/src/utils/config_utils.js
Use utility function for accessing the feature flag for etp2026 in etp-front. Always make a component dependent on the whole config instead of being dependent on the flag only.
> Et26 feature flag utility function

- etp-core/etp-backend/src/test/clj/solita/etp/service/energiatodistus_test.clj
- etp-front/README.md
Add ET2026 version to unit test data and make sure deleting a version 2026 draft works.
> AE-2564: add basic unit test capabilities for ET2026

- etp-core/etp-backend/src/main/clj/solita/etp/api/perusparannuspassi.clj
- etp-front/src/language/fi.json
- etp-front/src/language/sv.json
- etp-front/src/pages/energiatodistus/EnergiatodistusForm.svelte
- etp-front/src/pages/energiatodistus/ToolBar/toolbar.svelte
- etp-front/src/pages/energiatodistus/energiatodistus-api.js
Lisätty perustoiminnallisuus PPP:n lisäyksellä luonnostilaiselle ET26:lle. En kokenut tarvetta laittaa featureflagin taakse sillä toiminnon näkyvyys on riippuvainen ET26-olemassaolosta. Lisätty myös devauksen ajaksi indikaattori PPP:n lisäyksestä, jatko kehityksenä sitten lomake kunnolla kuntoon.
Tiketin kohtaa "Perusparannuspassi korvaa energiatodistuksen kohdat “Toimenpide-ehdotukset e-luvun parantamiseksi" ja "Suosituksia rakennuksen käyttöön ja ylläpitoon”. Sisältö jää lukutilaan.", en vielä toteuttanut, sillä en kokenut järkeväksi laittaa näitä vanhojen EnergiatodistustForm-komponenttien sisälle, ET26-formiahan meillä ei vielä ole luotuna
Lisäksi PR:ssä korjattu bugi aiemmin toteutetussa REST-rajapinnassa, priva-reitti vaati tuplavektorin.
> AE-2574: Add Perusparannuspassi functionality and localization updates
