solita/ara-etp

etp-core/etp-backend/src/main/clj/solita/etp/service/energiatodistus_pdf.clj
etp-core/etp-backend/src/test/clj/solita/etp/api/palveluvayla_test.clj

Old energy certificates (~2016 or so and older) have language set to null in database. A recent addition, which checked the language before trying to fetch certificates from S3 prevented old certificates from being fetched. It is unclear whether those old certificates have both language versions available, or just some.
Fix by trying to fetch certificates which have null language as before.
Fixed also energiatodistus-pdf/find-existing-pdf to actually check the result of calling file-exists?. This is needed for palveluväylä API to function, as it may try to fetch non-existing language versions based on accept-language.

Fix fetching old energy certificates without language set

---

etp-front/src/pages/valvonta-kaytto/manager.svelte
etp-front/src/pages/valvonta-kaytto/new-decision-order-actual-decision-toimenpide.svelte
etp-front/src/pages/valvonta-kaytto/new-penalty-decision-actual-decision-toimenpide.svelte
etp-front/src/pages/valvonta-kaytto/new-toimenpide-dialog.svelte
etp-front/src/pages/valvonta-kaytto/toimenpiteet.js

AE-2105: Pass all osapuolet only to kehotus toimenpidetype in käytönvalvonta, other toimenpidetypes use only owners
- Filter owners only in one place

AE-2105: Pass all osapuolet only to kehotus toimenpidetype in käytönvalvonta, other toimenpidetypes use only owners

---

etp-public/src/pages/aineistopalvelu-liittyminen-fi.svelte
etp-public/src/pages/aineistopalvelu-liittyminen-sv.svelte

AE-2083: Update wiki address to point to the new repository in public aineistopalvelu info page

AE-2083: Update wiki address to point to the new repository in public aineistopalvelu info page

---

etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_kaytto/toimenpide.clj
etp-core/etp-backend/src/test/clj/solita/etp/service/valvonta_kaytto/toimenpide_test.clj
etp-core/etp-backend/src/test/clj/solita/etp/service/valvonta_kaytto_test.clj
etp-core/etp-backend/src/test/clj/solita/etp/valvonta_kaytto/suljetus_valvonnan_uudelleenavaus.clj
etp-core/etp-db/src/main/sql/migration/repeatable/vk_template/r-0-vk-toimenpidetype.sql
etp-front/src/language/fi.json
etp-front/src/language/sv.json
etp-front/src/pages/valvonta-kaytto/manager.svelte
etp-front/src/pages/valvonta-kaytto/toimenpiteet.js

- Opens in ETP side by creating a new toimenpide of type Suljetun valvonnan uudelleenavaus
- Instructs the user to reopen the asia in asianhallinta manually

AE-2120: Implement reopening a closed käytönvalvonta

---

etp-front/src/pages/kayttaja/new-kayttaja.svelte

This fixes a crash of the frontend on creation of a new Pääkäyttäjä

AE-2142 Fill in None values for tittelis of emptyKayttaja

---

etp-public/src/components/info-block.svelte
etp-public/src/pages/energiatodistusrekisterin-aineistopalvelu-fi.svelte
etp-public/src/pages/energiatodistusrekisterin-aineistopalvelu-sv.svelte
etp-public/src/pages/energiatodistusrekisterin-rajapintapalvelu-fi.svelte
etp-public/src/pages/energiatodistusrekisterin-rajapintapalvelu-sv.svelte
etp-public/src/pages/tietojenluovutus-ja-rajapinnat-fi.svelte
etp-public/src/pages/tietojenluovutus-ja-rajapinnat-sv.svelte

Requested changes to Aineistot pages

---

etp-public/package-lock.json
etp-public/package.json
etp-public/src/main.js

- Internet Explorer 11 died on 15th of June 2022

Remove remove-whatwg-fetch from public

---

.github/workflows/ci-e2e-cypress.yml
e2e-tests/cypress/cypress.config.js
e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
e2e-tests/cypress/cypress/support/commands.js
e2e-tests/cypress/cypress/support/e2e.js
e2e-tests/cypress/docker-compose.yml
e2e-tests/cypress/override.yaml
etp-core/docker/docker-compose.yml
etp-core/etp-backend/src/main/clj/solita/etp/config.clj
etp-front/src/components/Link/Link.svelte
etp-front/src/pages/navigation/navigation-tab.svelte
etp-front/src/pages/valvonta-kaytto/henkilo-form.svelte
etp-front/src/pages/valvonta-kaytto/manager.svelte
etp-front/src/pages/valvonta-kaytto/new-decision-order-actual-decision-toimenpide.svelte
etp-front/src/pages/valvonta-kaytto/new-penalty-decision-actual-decision-toimenpide.svelte
etp-front/src/pages/valvonta-kaytto/new-toimenpide-dialog.svelte
etp-front/src/pages/valvonta-kaytto/toimenpide-osapuolet-table.svelte
etp-front/src/pages/valvonta-kaytto/toimenpiteet.js
etp-front/src/pages/valvonta-kaytto/toimenpiteet_test.js
etp-front/src/pages/valvonta-kaytto/valvonta-api.js

AE-1957: Filter available käytönvalvonta toimenpidetypes based on what are allowed from the current toimenpide
- Implement e2e tests for käytönvalvonta process

AE-1957: Filter available käytönvalvonta toimenpidetypes based on what are allowed from the current toimenpide

---

e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
etp-front/src/pages/valvonta-kaytto/manager.svelte
etp-front/src/pages/valvonta-kaytto/toimenpiteet.js
etp-front/src/pages/valvonta-kaytto/toimenpiteet_test.js

Implemented requested changes from AE-2150

AE-2150: Fixes to allowed käytönvalvonta toimenpidetypes

---

e2e-tests/cypress/cypress/e2e/kaytonvalvonta/kaytonvalvonta.cy.js
etp-front/src/pages/valvonta-kaytto/toimenpiteet.js
etp-front/src/pages/valvonta-kaytto/toimenpiteet_test.js

Requested changes described in Jira comments

AE-2156: Change primary toimenpide options in käytönvalvonta based on  user feedback

---

etp-core/etp-backend/src/main/clj/solita/etp/service/laatija.clj
etp-core/etp-backend/src/test/clj/solita/etp/service/laatija_test.clj
etp-core/etp-backend/src/test/resources/logback.xml

Hide non-active laatijas in public search

---

etp-public/src/pages/ethaku.svelte
etp-public/src/pages/laatijahaku.svelte

Missed breaking change
https://svelte.dev/docs/v4-migration-guide#default-slot-bindings

Fix pagination in laatijahaku when using Svelte 4

---

etp-front/src/pages/energiatodistus/korvaavuus/korvattu.svelte

Once again problem with too many reactive components. Apparently checkbox also modifying the value, and using bind caused problems.

Fix "Korvaa energiatodistuksen" checkbox

---

etp-front/src/pages/energiatodistus/energiatodistus-haku/querybuilder/query-inputs/alakayttotarkoitus-input.svelte
etp-front/src/pages/energiatodistus/energiatodistus-haku/querybuilder/query-inputs/kayttotarkoitus-input.svelte
etp-front/src/pages/energiatodistus/energiatodistus-haku/querybuilder/query-inputs/versioluokka-input.svelte

Fix Käyttötarkoitusluokka search

---

etp-front/src/pages/energiatodistus/ToolBar/toolbar.svelte
etp-front/src/pages/energiatodistus/signing/SigningDialog.svelte

Revert "Allow selecting the new signing method for a tester"

---

etp-front/src/pages/energiatodistus/ToolBar/toolbar.svelte
etp-front/src/pages/energiatodistus/signing/SigningDialog.svelte

Revert "Revert "Revert "Allow selecting the new signing method for a tester"""

---

etp-front/package-lock.json
etp-public/package-lock.json

Fixes applied by this command are semver compatible

AE-2264: Run `npm audit fix`

---

etp-core/etp-backend/src/main/clj/solita/etp/service/energiatodistus_destruction.clj

- Writes a log when finished
- Uses similar language as previous logs

AE-2282: Improve energiatodistus destrcution logging

---

etp-core/etp-backend/src/main/clj/solita/etp/service/energiatodistus_destruction.clj
etp-core/etp-backend/src/main/clj/solita/etp/service/valvonta_oikeellisuus/asha.clj
etp-core/etp-backend/src/test/clj/solita/etp/service/energiatodistus_destruction_test.clj

- Change the valvonta type in test to be such that it creates a document.
- Reveal file-path from valvonta-oikeellisuus.asha
- Add document removal step

AE-2282: Add removal of toimenpide document

---

etp-core/etp-backend/src/main/clj/solita/etp/service/energiatodistus_destruction.clj

For some reason getting the tag succeeds but deletion does not

AE-2318: Fix polling logic

---

etp-core/etp-backend/src/main/clj/solita/etp/service/energiatodistus_destruction.clj

Tagging an object and deleting it right after was a bad idea. It takes time for AWS IAM to realize that the tag exists

AE-2318: Remove the polling

---

etp-core/etp-backend/src/main/clj/solita/etp/service/laskutus.clj

This reverts commit 1b6bcf9b0ae920da34977ee043a709147375d9ba.
The change (or something that supersedes it) will need to be done again later for production use.

Revert "AE-2301: Change 7010 -> 7000 in Kieku messages"

---

etp-core/etp-backend/src/main/clj/solita/etp/service/suomifi_viestit_rest.clj

This may be useful for problem solving purposes

AE-2502 Log the messageId number we get for submitted suomi.fi viestit

---

etp-core/README.md
etp-core/docker/docker-compose.yml
etp-core/docker/start.sh

This PR adds support for Podman as an alternative for Docker.

Add Podman support to local development environment

---

etp-public/src/components/info-tooltip.svelte
etp-public/src/components/table-laatijahaku-filter.svelte
etp-public/src/components/tilastot-chart.svelte
etp-public/src/pages/energiatodistusrekisterin-rajapintapalvelu-fi.svelte
etp-public/src/pages/energiatodistusrekisterin-rajapintapalvelu-sv.svelte
etp-public/src/pages/rekisteroitumisohjeet-fi.svelte
etp-public/src/pages/rekisteroitumisohjeet-sv.svelte
etp-public/src/pages/tietojenluovutus-ja-rajapinnat-fi.svelte
etp-public/src/pages/tietojenluovutus-ja-rajapinnat-sv.svelte
etp-public/src/pages/tietosuojaseloste-aineistopalvelun-kayttajarekisteri-fi.svelte
etp-public/src/pages/tietosuojaseloste-aineistopalvelun-kayttajarekisteri-sv.svelte

Parannettu useamman komponentin saavutettavuutta ja samalla poistettu käyttämättömiä css-selectoreita.

AE-2642: Julkisen palvelun front-end saavutettavuus varoitukset
